# QUIZ GAME START UP

# THIS GAME IS A BOT ASKING BASIC QUESTIONS WITH ONE WORDED ANSWERS
print("THIS GAME IS A BOT ASKING FOUR BASIC QUESTIONS WITH ONE WORDED ANSWERS...")
# WE HAVE FOUR QUESTIONS
# LET'S SEE IF THE USER WANTS TO PLAY
playerInput = input("DO YOU WISH TO SEEK YOUR FORTUNE...")

if playerInput.lower() != "yes":
    quit()


print("Alllrrrriiiight then :/")
score = 0
# QUESTION ONE: "WHAT COLOR WERE THE FIRSTS TESLAS"  (WHITE)
print("WHAT COLOR WERE THE FIRST TESLAS?")
# QUESTION TWO: "WHAT YEAR WAS WW2"   (1939)
print("WHAT YEAR WAS WW2?")
# QUESTION THREE: "WHAT WAS OUR FIRST PRESIDENTS LAST NAME"    (WASHINGTON)
print("WHAT WAS OUR FIRST PRESIDENTS LAST NAME?" )
# QUESTION FOUR: "WHAT YEAR WAS THE GREAT DEPRESSION START"   (1929)
print("WHAT YEAR WAS THE GREAT DEPRESSION START?")

# NOW LET'S COUNT OUR SOLUTIONS
# NPC CORRECT OPTIONS:
# "Woohooo! Nice one"
# "omg, who are you! Great Job!"
# "Lets GoOoOoOoOoOOoOo"
# "You so smart, you human, you"

# NPC INCORRECT OPTIONS:
# "WRONG, try again though, you got this"
# "Not even close, but still great effort <3"
# "Nope."
# "Think again"

# END OF QUIZ REACTION: "GOOD JOB, YOU ARE FINISHED"
